version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./persistent/storage:/var/www/html/storage:rw
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
    ports:
      - '80:80'
      - '443:443'

  database:
    image: mysql
    volumes:
      - ./persistent/bbdd:/var/lib/mysql
      - ./persistent/bbdd:/var/backups
      - ./backup.sh:/var/backup.sh
    environment:
      MYSQL_DATABASE: foria
      MYSQL_USER: foriauser
      MYSQL_PASSWORD: te9n#mF3a#cAAGP8
      MYSQL_ROOT_PASSWORD: cM#@j22@MwdV#Nsr

