version: '3'
services:
  backend:
    # image: registry/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      # - ./backend:/var/www/html
      - storage:/var/www/html/storage:rw
    depends_on:
      - database

  frontend:
    # image: registry/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
    ports:
      - '10088:80'
      - '10188:443'


  database:
    image: mysql
    command: --log_bin_trust_function_creators=1
    volumes:
      - bbdd:/var/lib/mysql
    environment:
      MYSQL_DATABASE: foria
      MYSQL_USER: foriauser
      MYSQL_PASSWORD: dufh4342jchdd
      MYSQL_ROOT_PASSWORD: 64ghfgsjh3j1

volumes:
  storage:
  bbdd:
